### ISSUE TITLE
Fix old lookup_transfer reference in episodes_of_care function

### ISSUE THREAD

**Issue by marchenaromk** [GEMINI-Medicine/Rgemini#155]
The lookup_transfer table in report_db has been changed from only including acute care transfers, to including any institution type transfer. Hence, the column names for this table have changed. The `episodes_of_care` function references two old columns `acute_transfer_in` and `acute_transfer_out` which have since been deprecated. My proposal is to either change the column reference in the script or change the lookup transfer table column names before merging with admdad.

**Comment by loffleraSMH** [comment]
Hi @marchenaromk, thanks for flagging this! I would suggest we change the code in the Rgemini function. Ideally, we can make it work for both versions of the `lookup_transfer` table (since most HPC users will still be working with the old version for a while). I'm happy to develop the code for this.
