### ISSUE TITLE
Move mLAPS function from GEMINIpkg to Rgemini

### ISSUE THREAD

**Issue by loffleraSMH** [GEMINI-Medicine/Rgemini#30]
## New Feature Request

Add mLAPS function to `Rgemini` and deprecate from `GEMINIpkg`

Suppress warnings, clean up subfunction (maybe open new issue).

Any suggested developers?

* 

Any suggested reviewers?

*

**Comment by vaakesan-SMH** [comment]
Note that warnings are currently suppressed when calculating max BUN and min creatinine. This workaround was done so that the unit tests can be run. Look to treat this more robustly (e.g. only calculate min/max when these vectors are not `NA`).

Otherwise, `laps_assign_test()` has some very "hack-y" and hard to understand logic. Would be nice to improve for clarity.

`mlaps()` and `loop_mlaps()` can be ported over directly. Functions have already been developed and only need review as per the Code Review Checklist.
